<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240907183926 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE question (
                            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            text TEXT NOT NULL,
                            created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, 
                            PRIMARY KEY(id))');

        $this->addSql('CREATE TABLE answer (
                            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            question_id INT,
                            text TEXT NOT NULL, 
                            is_correct BOOLEAN NOT NULL,
                            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,                         
                            PRIMARY KEY(id))');

        $this->addSql('CREATE INDEX IDX_DADD4A251E27F6BF ON answer (question_id)');

        $this->addSql('CREATE TABLE user_answer (
                            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                            user_uuid UUID NOT NULL, 
                            question_id INT NOT NULL, 
                            answer_id INT NOT NULL, 
                            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,     
                            PRIMARY KEY(id))');

        $this->addSql('CREATE INDEX IDX_BF8F51181E27F6BF ON user_answer (question_id)');
        $this->addSql('CREATE INDEX IDX_BF8F5118AA334807 ON user_answer (answer_id)');

        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A251E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_answer ADD CONSTRAINT FK_BF8F51181E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_answer ADD CONSTRAINT FK_BF8F5118AA334807 FOREIGN KEY (answer_id) REFERENCES answer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->fillTables();
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE answer DROP CONSTRAINT FK_DADD4A251E27F6BF');
        $this->addSql('ALTER TABLE user_answer DROP CONSTRAINT FK_BF8F51181E27F6BF');
        $this->addSql('ALTER TABLE user_answer DROP CONSTRAINT FK_BF8F5118AA334807');
        $this->addSql('DROP TABLE answer');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE user_answer');
    }

    public function fillTables() :void
    {
        $this->addSql("INSERT INTO question (id, text, created_at) VALUES 
                                                (1, '1 + 1 =', NOW()),
                                                (2, '2 + 2 =', NOW()),
                                                (3, '3 + 3 =', NOW()),
                                                (4, '4 + 4 =', NOW()),
                                                (5, '5 + 5 =', NOW()),
                                                (6, '6 + 6 =', NOW()),
                                                (7, '7 + 7 =', NOW()),
                                                (8, '8 + 8 =', NOW()),
                                                (9, '9 + 9 =', NOW()),
                                                (10, '10 + 10 =', NOW())
                                                ");


        $this->addSql("INSERT INTO answer (question_id, text, is_correct, created_at)
                            VALUES (1, '3', false, NOW()),
                                   (1, '2', true, NOW()),
                                   (1, '0', false, NOW()),
                                   
                                   (2, '4', true, NOW()),
                                   (2, '3 + 1', true, NOW()),
                                   (2, '10', false, NOW()),
                                   
                                   (3, '1 + 5', true, NOW()),
                                   (3, '1', false, NOW()),
                                   (3, '6', true, NOW()),
                                   (3, '2 + 4', true, NOW()),
                                   
                                   (4, '8', true, NOW()),
                                   (4, '4', false, NOW()),
                                   (4, '0', false, NOW()),
                                   (4, '0 + 8', true, NOW()),
                                   
                                   (5, '6', false, NOW()),
                                   (5, '18', false, NOW()),
                                   (5, '10', true, NOW()),
                                   (5, '9', false, NOW()),
                                   (5, '0', false, NOW()),
                                   
                                   (6, '3', false, NOW()),
                                   (6, '9', false, NOW()),
                                   (6, '0', false, NOW()),
                                   (6, '12', true, NOW()),
                                   (6, '5 + 7', true, NOW()),
                                   
                                   (7, '5', false, NOW()),
                                   (7, '14', true, NOW()),
                                   
                                   (8, '16', true, NOW()),
                                   (8, '12', false, NOW()),
                                   (8, '9', false, NOW()),
                                   (8, '5', false, NOW()),
                                   
                                   (9, '18', true, NOW()),
                                   (9, '9', false, NOW()),
                                   (9, '17 + 1', true, NOW()),
                                   (9, '2 + 16', true, NOW()),
                                   
                                   (10, '0', false, NOW()),
                                   (10, '2', false, NOW()),
                                   (10, '8', false, NOW()),
                                   (10, '20', true, NOW())
                                                               ");
    }
}
